name: End-to-End Tests

on:
    pull_request:
    push:
        branches:
            - trunk
            - 'release/**'
            - 'wp/**'

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

jobs:
    e2e-playwright:
        name: Playwright - ${{ matrix.part }}
        runs-on: 'ubuntu-24.04'
        permissions:
            contents: read
        if: ${{ github.repository == 'WordPress/gutenberg' || github.event_name == 'pull_request' }}
        strategy:
            fail-fast: false
            matrix:
                part: [1, 2, 3, 4, 5, 6, 7, 8]
                totalParts: [8]

        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}
                  persist-credentials: false

            - name: Setup Node.js and install dependencies
              uses: ./.github/setup-node

            - name: Npm build
              run: npm run build -- --skip-types

            - name: Install Playwright dependencies
              run: |
                  npx playwright install chromium firefox webkit --with-deps

            - name: Install WordPress and start the server
              run: |
                  npm run wp-env-test start

            - name: Run the tests
              env:
                  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
                  SHARD_PART: ${{ matrix.part }}
                  SHARD_TOTAL: ${{ matrix.totalParts }}
              run: |
                  xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run test:e2e -- --shard="${SHARD_PART}/${SHARD_TOTAL}"

            - name: Archive debug artifacts (screenshots, traces)
              uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
              if: ${{ !cancelled() }}
              with:
                  name: failures-artifacts--${{ matrix.part }}
                  path: artifacts/test-results
                  if-no-files-found: ignore

            - name: Archive blob reports (HTML)
              uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
              if: ${{ !cancelled() }}
              with:
                  name: blob-reports--${{ matrix.part }}
                  path: blob-report
                  if-no-files-found: ignore

            - name: Archive flaky tests report
              uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
              if: ${{ !cancelled() }}
              with:
                  name: flaky-tests-report--${{ matrix.part }}
                  path: flaky-tests
                  if-no-files-found: ignore

    merge-artifacts:
        name: Merge Artifacts
        if: ${{ !cancelled() }}
        needs: [e2e-playwright]
        runs-on: 'ubuntu-24.04'
        permissions:
            contents: read
        outputs:
            has-flaky-test-report: ${{ !!steps.merge-flaky-tests-reports.outputs.artifact-id }}
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}
                  persist-credentials: false

            - name: Setup Node.js and install dependencies
              uses: ./.github/setup-node

            - name: Merge failures artifacts
              uses: actions/upload-artifact/merge@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
              # Don't fail the job if there aren't any artifacts to merge.
              continue-on-error: true
              with:
                  name: failures-artifacts
                  # Retain the merged artifacts in case of a rerun.
                  pattern: failures-artifacts*
                  delete-merged: true

            - name: Merge flaky tests reports
              id: merge-flaky-tests-reports
              uses: actions/upload-artifact/merge@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
              continue-on-error: true
              with:
                  name: flaky-tests-report
                  pattern: flaky-tests-report*
                  delete-merged: true

            - name: Merge blob reports
              uses: actions/upload-artifact/merge@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
              continue-on-error: true
              with:
                  name: blob-reports-merged
                  pattern: blob-reports--*
                  delete-merged: true

            - name: Download merged blob reports
              uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
              continue-on-error: true
              with:
                  name: blob-reports-merged
                  path: all-blob-reports

            - name: Merge blob reports into HTML report
              run: npx playwright merge-reports --reporter html ./all-blob-reports
              continue-on-error: true

            - name: Upload merged HTML report
              uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
              continue-on-error: true
              with:
                  name: html-report--attempt-${{ github.run_attempt }}
                  path: playwright-report
                  if-no-files-found: ignore

    report-to-issues:
        name: Report to GitHub
        needs: [merge-artifacts]
        if: ${{ needs.merge-artifacts.outputs.has-flaky-test-report == 'true' }}
        runs-on: 'ubuntu-24.04'
        permissions:
            contents: read
            issues: write
            pull-requests: write
        steps:
            # Checkout defaults to using the branch which triggered the event, which
            # isn't necessarily `trunk` (e.g. in the case of a merge).
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  ref: trunk
                  show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}
                  persist-credentials: false

            - uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
              # Don't fail the job if there isn't any flaky tests report.
              continue-on-error: true
              with:
                  name: flaky-tests-report
                  path: flaky-tests

            - name: Setup Node.js and install dependencies
              uses: ./.github/setup-node

            - name: Npm build
              run: npm run build -- --skip-types

            - name: Report flaky tests
              uses: ./packages/report-flaky-tests
              with:
                  repo-token: '${{ secrets.GITHUB_TOKEN }}'
                  label: '[Type] Flaky Test'
                  artifact-path: flaky-tests
